version: '2'
services:
  fpm:
    build: docker/php
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    environment:
      working_dir: /var/www/html

  nginx:
    build: docker/Nginx
    volumes:
      - ./docker/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/Nginx/upx.conf:/etc/nginx/conf.d/upx.conf
      - ./Logs/:/var/log/nginx
    ports:
      - "80:80"
    links:
      - fpm

  composer:
    build: docker/composer
    volumes:
      - ./app:/home/web

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tasks

    volumes: 
      - ./data:/var/lib/mysql
