version: '2'
services:
  fpm:
    build: docker/php
    restart: always
    volumes:
      - ./app:/var/www/html
    ports:
      - "9000:9000"
    environment:
      working_dir: /var/www/html

  nginx:
    build: docker/Nginx
    restart: always
    volumes:
      - ./docker/Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/Nginx/upx.conf:/etc/nginx/conf.d/upx.conf
      - ./Logs/:/var/log/nginx
    ports:
      - "80:80"
    links:
      - fpm

  composer:
    build: docker/composer
    volumes:
      - ./app:/home/web
